name = "onbored-worker"
main = "src/worker.ts"
compatibility_date = "2025-07-17"

[observability]
enabled = true

[env.staging]
name = "onbored-ingestion-staging"

[[env.staging.unsafe.bindings]]
name = "PROJECT_RATE_LIMITER"
type = "ratelimit"
namespace_id = "1002"
simple = { limit = 1000, period = 60 }

[[env.staging.kv_namespaces]]
binding = "CUSTOMER_ACCOUNT_CACHE"
id = "5c635f2b556844dbb002efc4b2fd0f56"
preview_id = "2f39fe7972b6408582abd3e4b07e6f8e"

[env.production]
name = "onbored-ingestion"

[[env.production.unsafe.bindings]]
name = "PROJECT_RATE_LIMITER"
type = "ratelimit"
namespace_id = "1003"
simple = { limit = 10000, period = 60 }

[[env.production.kv_namespaces]]
binding = "CUSTOMER_ACCOUNT_CACHE"
id = "5c0c366a1a87467789e4aeb4538352da"
preview_id = "2f39fe7972b6408582abd3e4b07e6f8e"